const employeeList = [
    {
      id: "01",
      firstname: "Robert",
      lastname: "Kyle",
      age: 40,
      gender: "Male",
      phoneNumber: "0856664444",
      position: "Manager",
      department: "Marketing",
      salary: 80000,
    },
    {
      id: "02",
      firstname: "Michael",
      lastname: "Chang",
      age: 30,
      gender: "Male",
      phoneNumber: "0899999999",
      position: "Assistant Manager",
      department: "IT",
      salary: 50000,
    },
    {
      id: "03",
      firstname: "Diana",
      lastname: "Mcpic",
      age: 26,
      gender: "Female",
      phoneNumber: "0536669999",
      position: "Executive",
      department: "Marketing",
      salary: 35000,
    },
    {
      id: "04",
      firstname: "Sally",
      lastname: "Walker",
      age: 32,
      gender: "Female",
      phoneNumber: "0995551111",
      position: "Accountant",
      department: "Accounting",
      salary: 40000,
    },
    {
      id: "05",
      firstname: "Ellie",
      lastname: "Schnap",
      age: 50,
      gender: "Female",
      phoneNumber: "0912223333",
      position: "Manager",
      department: "Accounting",
      salary: 40000,
    },
    {
      id: "06",
      firstname: "Roy",
      lastname: "Lanler",
      age: 30,
      gender: "Male",
      phoneNumber: "0899999999",
      position: "Manager",
      department: "IT",
      salary: 60000,
    },
  ];
  
  export default employeeList;